package Bus;







/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import airline.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.UIManager;



/**
 *
 * @author 786 TRADERS
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
     javax.swing.JLabel lblImg,lblTtl;
     javax.swing.JButton btnDisplay1;
    public Welcome() {
        initComponents();
         lblImg = new javax.swing.JLabel();
        lblImg.setBounds(0,0,460, 588);
        jPanel2.setOpaque(false);
        
        lblTtl =new javax.swing.JLabel();
        lblTtl.setBackground(new java.awt.Color(0, 255, 255));
        lblTtl.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 40)); // NOI18N
        lblTtl.setForeground(new java.awt.Color(255, 255, 255));
        lblTtl.setText("Bus Reservation  ");
        lblTtl.setBounds(20, 8, 450, 80);
        btnDisplay1=new JButton("Log Out");
        btnDisplay1.setBackground(new java.awt.Color(0, 0, 204));
        btnDisplay1.setForeground(new java.awt.Color(255,255,255));
        btnDisplay1.setBounds(100,500,220,30);
        add(btnDisplay1);
        btnDisplay1.addActionListener(new ActionListener(){  
         public void actionPerformed(ActionEvent e){  
            new  Loginframe();
            dispose();
    }  
    });  
        
        
     logoBtime.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        new Destination().setVisible(true);
        dispose();
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        
    }
}); 
      logoBfrgt.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
       new CancelationForm().setVisible(true);
        dispose();
    }
    public void mouseExited(java.awt.event.MouseEvent evt) {
        
    }
}); 
        scale1(lblImg);
        add(lblTtl);
         add(lblImg);
        scaleImage1();
        scaleImage2();
         this.setSize(470, 600);
        setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("D:\\Project\\Airline\\src\\airline\\Image\\resizer.jpg"));
    }
     public void scale1(javax.swing.JLabel j) {
            ImageIcon img=new ImageIcon("D:\\Project\\Airline\\src\\airline\\Image\\createBackground.jpeg");
        Image img1 = img.getImage();
        Image scale = img1.getScaledInstance(j.getWidth(), j.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(scale);
        j.setIcon(img2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        fromCBox = new javax.swing.JComboBox<>();
        toCBox = new javax.swing.JComboBox<>();
        serachbtn = new javax.swing.JButton();
        dateField = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        logoBtime = new javax.swing.JLabel();
        logoBfrgt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));
        panelSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        lblTitle.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 102, 51));
        lblTitle.setText("Search Bus");

        fromCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karachi" }));
        fromCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCBoxActionPerformed(evt);
            }
        });

        toCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lahore" }));

        serachbtn.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        serachbtn.setText("Search");
        serachbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 0, true));
        serachbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(fromCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSearchLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(serachbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toCBox, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(fromCBox))
                .addGap(18, 18, 18)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(serachbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(logoBtime, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(logoBfrgt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoBtime, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoBfrgt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void scaleImage1()
    {
        ImageIcon icon =new ImageIcon("D:\\Project\\Airline\\src\\airline\\Image\\bustime.jpg");
        Image img= icon.getImage();
        Image  imgScale =img.getScaledInstance(logoBtime.getWidth(),logoBtime.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon sImg= new ImageIcon(imgScale);
        logoBtime.setIcon(sImg);
            
    }
     public void scaleImage2()
    {
        ImageIcon icon =new ImageIcon("D:\\Project\\Airline\\src\\airline\\Image\\cancel.png");
        Image img= icon.getImage();
        Image  imgScale =img.getScaledInstance(logoBfrgt.getWidth(),logoBfrgt.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon sImg= new ImageIcon(imgScale);
        logoBfrgt.setIcon(sImg);
        
    }
           
    
    private void fromCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCBoxActionPerformed

    private void serachbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachbtnActionPerformed
        // TODO add your handling code here:
        try
        {
        String from = fromCBox.getSelectedItem().toString();
        String to =toCBox.getSelectedItem().toString();
        SimpleDateFormat sdf= new SimpleDateFormat("dd/MM/yyyy");
        String data =sdf.format(dateField.getDate());
        dispose();
        new BusInfo(from, to, data);
        }
        catch(Exception e)
        {
             dateField.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.RED));
        }
         
        
        
        
        
        
        
    }//GEN-LAST:event_serachbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JComboBox<String> fromCBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel logoBfrgt;
    private javax.swing.JLabel logoBtime;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JButton serachbtn;
    private javax.swing.JComboBox<String> toCBox;
    // End of variables declaration//GEN-END:variables
}
